### ISSUE TITLE
Put WOA observations onto a grid

### ISSUE THREAD

**Issue by profseth** [briochemc/WorldOceanAtlasTools.jl#18]
I would like to put WOA observations onto an AIBECS grd. It seems like this is part of the functionality, but the documentation does not describe how to accomplish this.

See documentation: Fitting a 3D field from WOA to another grid

**Comment by briochemc** [comment]
Done! With the new version (v0.6.0, just submitted for a new release) you can now use, e.g., `fit_to_grid(grd, "PO4")`, as explained [in the current "dev" docs](https://briochemc.github.io/WorldOceanAtlasTools.jl/dev/#Regridding-WOA-data-to-an-AIBECS-grid) (soon to be the new "stable").
