### ISSUE TITLE
GitHub actions dont trigger upon PR

### ISSUE THREAD

**Issue by gaelforget** [briochemc/WorldOceanAtlasTools.jl#23]
I tested https://github.com/briochemc/WorldOceanAtlasTools.jl/pull/21 locally but GitHub repo does not trigger

**Comment by gaelforget** [comment]
I see now that "7 workflows awaiting approval" on the PR

**Comment by briochemc** [comment]
Yes, sorry, I must have set the workflows to require authorization for first contributions. I ran the workflow and it looks like it worked :)
